/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class atb_alg_SSA */

#ifndef _Included_atb_alg_SSA
#define _Included_atb_alg_SSA
#ifdef __cplusplus
extern "C" {
#endif
#undef atb_alg_SSA_FOCUS_TRAVERSABLE_UNKNOWN
#define atb_alg_SSA_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef atb_alg_SSA_FOCUS_TRAVERSABLE_DEFAULT
#define atb_alg_SSA_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef atb_alg_SSA_FOCUS_TRAVERSABLE_SET
#define atb_alg_SSA_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef atb_alg_SSA_TOP_ALIGNMENT
#define atb_alg_SSA_TOP_ALIGNMENT 0.0f
#undef atb_alg_SSA_CENTER_ALIGNMENT
#define atb_alg_SSA_CENTER_ALIGNMENT 0.5f
#undef atb_alg_SSA_BOTTOM_ALIGNMENT
#define atb_alg_SSA_BOTTOM_ALIGNMENT 1.0f
#undef atb_alg_SSA_LEFT_ALIGNMENT
#define atb_alg_SSA_LEFT_ALIGNMENT 0.0f
#undef atb_alg_SSA_RIGHT_ALIGNMENT
#define atb_alg_SSA_RIGHT_ALIGNMENT 1.0f
#undef atb_alg_SSA_serialVersionUID
#define atb_alg_SSA_serialVersionUID -7644114512714619750i64
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef atb_alg_SSA_serialVersionUID
#define atb_alg_SSA_serialVersionUID 4613797578919906343i64
/* Inaccessible static: dbg */
#undef atb_alg_SSA_INCLUDE_SELF
#define atb_alg_SSA_INCLUDE_SELF 1L
#undef atb_alg_SSA_SEARCH_HEAVYWEIGHTS
#define atb_alg_SSA_SEARCH_HEAVYWEIGHTS 1L
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: readObjectCallbacks */
/* Inaccessible static: managingFocusForwardTraversalKeys */
/* Inaccessible static: managingFocusBackwardTraversalKeys */
/* Inaccessible static: suppressDropSupport */
/* Inaccessible static: checkedSuppressDropSupport */
#undef atb_alg_SSA_NOT_OBSCURED
#define atb_alg_SSA_NOT_OBSCURED 0L
#undef atb_alg_SSA_PARTIALLY_OBSCURED
#define atb_alg_SSA_PARTIALLY_OBSCURED 1L
#undef atb_alg_SSA_COMPLETELY_OBSCURED
#define atb_alg_SSA_COMPLETELY_OBSCURED 2L
#undef atb_alg_SSA_WHEN_FOCUSED
#define atb_alg_SSA_WHEN_FOCUSED 0L
#undef atb_alg_SSA_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define atb_alg_SSA_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef atb_alg_SSA_WHEN_IN_FOCUSED_WINDOW
#define atb_alg_SSA_WHEN_IN_FOCUSED_WINDOW 2L
#undef atb_alg_SSA_UNDEFINED_CONDITION
#define atb_alg_SSA_UNDEFINED_CONDITION -1L
#undef atb_alg_SSA_IS_DOUBLE_BUFFERED
#define atb_alg_SSA_IS_DOUBLE_BUFFERED 0L
#undef atb_alg_SSA_ANCESTOR_USING_BUFFER
#define atb_alg_SSA_ANCESTOR_USING_BUFFER 1L
#undef atb_alg_SSA_IS_PAINTING_TILE
#define atb_alg_SSA_IS_PAINTING_TILE 2L
#undef atb_alg_SSA_IS_OPAQUE
#define atb_alg_SSA_IS_OPAQUE 3L
#undef atb_alg_SSA_KEY_EVENTS_ENABLED
#define atb_alg_SSA_KEY_EVENTS_ENABLED 4L
#undef atb_alg_SSA_FOCUS_INPUTMAP_CREATED
#define atb_alg_SSA_FOCUS_INPUTMAP_CREATED 5L
#undef atb_alg_SSA_ANCESTOR_INPUTMAP_CREATED
#define atb_alg_SSA_ANCESTOR_INPUTMAP_CREATED 6L
#undef atb_alg_SSA_WIF_INPUTMAP_CREATED
#define atb_alg_SSA_WIF_INPUTMAP_CREATED 7L
#undef atb_alg_SSA_ACTIONMAP_CREATED
#define atb_alg_SSA_ACTIONMAP_CREATED 8L
#undef atb_alg_SSA_CREATED_DOUBLE_BUFFER
#define atb_alg_SSA_CREATED_DOUBLE_BUFFER 9L
#undef atb_alg_SSA_CREATED_VOLATILE_DOUBLE_BUFFER
#define atb_alg_SSA_CREATED_VOLATILE_DOUBLE_BUFFER 10L
#undef atb_alg_SSA_IS_PRINTING
#define atb_alg_SSA_IS_PRINTING 11L
#undef atb_alg_SSA_IS_PRINTING_ALL
#define atb_alg_SSA_IS_PRINTING_ALL 12L
#undef atb_alg_SSA_IS_REPAINTING
#define atb_alg_SSA_IS_REPAINTING 13L
#undef atb_alg_SSA_WRITE_OBJ_COUNTER_FIRST
#define atb_alg_SSA_WRITE_OBJ_COUNTER_FIRST 14L
#undef atb_alg_SSA_RESERVED_1
#define atb_alg_SSA_RESERVED_1 15L
#undef atb_alg_SSA_RESERVED_2
#define atb_alg_SSA_RESERVED_2 16L
#undef atb_alg_SSA_RESERVED_3
#define atb_alg_SSA_RESERVED_3 17L
#undef atb_alg_SSA_RESERVED_4
#define atb_alg_SSA_RESERVED_4 18L
#undef atb_alg_SSA_RESERVED_5
#define atb_alg_SSA_RESERVED_5 19L
#undef atb_alg_SSA_RESERVED_6
#define atb_alg_SSA_RESERVED_6 20L
#undef atb_alg_SSA_WRITE_OBJ_COUNTER_LAST
#define atb_alg_SSA_WRITE_OBJ_COUNTER_LAST 21L
#undef atb_alg_SSA_REQUEST_FOCUS_DISABLED
#define atb_alg_SSA_REQUEST_FOCUS_DISABLED 22L
/* Inaccessible static: class_00024javax_00024swing_00024JComponent_00024KeyboardState */
/* Inaccessible static: class_00024javax_00024swing_00024event_00024AncestorListener */
/* Inaccessible static: class_00024java_00024beans_00024VetoableChangeListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef atb_alg_SSA_serialVersionUID
#define atb_alg_SSA_serialVersionUID 50i64
#undef atb_alg_SSA_SMALLEST_MODULE_HEIGHT
#define atb_alg_SSA_SMALLEST_MODULE_HEIGHT 30L
#undef atb_alg_SSA_SMALLEST_MODULE_WIDTH
#define atb_alg_SSA_SMALLEST_MODULE_WIDTH 30L
#undef atb_alg_SSA_NW_HANDLE
#define atb_alg_SSA_NW_HANDLE 0L
#undef atb_alg_SSA_N_HANDLE
#define atb_alg_SSA_N_HANDLE 1L
#undef atb_alg_SSA_NE_HANDLE
#define atb_alg_SSA_NE_HANDLE 2L
#undef atb_alg_SSA_E_HANDLE
#define atb_alg_SSA_E_HANDLE 3L
#undef atb_alg_SSA_SE_HANDLE
#define atb_alg_SSA_SE_HANDLE 4L
#undef atb_alg_SSA_S_HANDLE
#define atb_alg_SSA_S_HANDLE 5L
#undef atb_alg_SSA_SW_HANDLE
#define atb_alg_SSA_SW_HANDLE 6L
#undef atb_alg_SSA_W_HANDLE
#define atb_alg_SSA_W_HANDLE 7L
/* Inaccessible static: mdiForm */
/* Inaccessible static: drawPane */
/* Inaccessible static: parent */
/* Inaccessible static: mdiForm */
#undef atb_alg_SSA_serialVersionUID
#define atb_alg_SSA_serialVersionUID 50i64
/* Inaccessible static: drawPane */
#undef atb_alg_SSA_VISUALISATION_MODE
#define atb_alg_SSA_VISUALISATION_MODE 0L
#undef atb_alg_SSA_ALGORITHM_MODE
#define atb_alg_SSA_ALGORITHM_MODE 1L
#undef atb_alg_SSA_serialVersionUID
#define atb_alg_SSA_serialVersionUID 50i64
/* Inaccessible static: mdiForm */
/*
 * Class:     atb_alg_SSA
 * Method:    doSSA
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_atb_alg_SSA_doSSA(JNIEnv * env, jclass obj, jstring sFileName);

#ifdef __cplusplus
}
#endif
#endif
